apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web3-smartwatch-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - api.web3smartwatch.com
    secretName: web3-smartwatch-tls
  rules:
  - host: api.web3smartwatch.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web3-smartwatch-server
            port:
              number: 80 