apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web3-smartwatch-ingress
  namespace: web3-smartwatch
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.smartwatch.bardplus.dev
      secretName: web3-smartwatch-tls
  rules:
    - host: api.smartwatch.bardplus.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web3-smartwatch-server
                port:
                  number: 80 