apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web3-smartwatch

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cluster-issuer.yaml
  - configmap.yaml
  # secrets.yaml is not included here as it contains sensitive information
  # and should be applied separately

commonLabels:
  app.kubernetes.io/name: web3-smartwatch
  app.kubernetes.io/instance: prod 