name: Go Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Generate code
        run: go generate ./...
      - name: Run Go tests
        run: go test -v ./...
      - name: Build
        run: go build -v ./...